export const overallDeals = [
  {
    date: "2025-04-01",
    transactionType: "Sale",
    dealType: "offplan",
    projectName: "Sunset Villas",
    unitNo: "A101",
    developerName: "Golden Estates",
    propertyType: "Villa",
    noOfBr: 4,
    clientName: "John Doe",
    agentName: "Sarah Ali",
    team: "Dream Team",
    propertyPrice: 1500000,
    grossCommissionInclVAT: 75000,
    grossCommission: 70500,
    vat: 4500,
    mondusCommission: 5000,
    leadSource: "Portal",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 25000,
    secondPaymentReceived: 25000,
    thirdPaymentReceived: 25000,
    totalPaymentReceived: 75000,
    amountReceivable: 0,
  },
  {
    date: "2025-03-28",
    transactionType: "Rent",
    dealType: "secondary",
    projectName: "Ocean Heights",
    unitNo: "1203",
    developerName: "Skyline Group",
    propertyType: "Apartment",
    noOfBr: 2,
    clientName: "Jane Smith",
    agentName: "Omar Khalid",
    team: "Elite Realty",
    propertyPrice: 120000,
    grossCommissionInclVAT: 6300,
    grossCommission: 6000,
    vat: 300,
    mondusCommission: 1000,
    leadSource: "Referral",
    invoiceStatus: "Not Invoiced",
    paymentReceived: false,
    firstPaymentReceived: 0,
    secondPaymentReceived: 0,
    thirdPaymentReceived: 0,
    totalPaymentReceived: 0,
    amountReceivable: 6300,
  },
  {
    date: "2025-03-22",
    transactionType: "Sale",
    dealType: "offplan",
    projectName: "Green Meadows",
    unitNo: "B203",
    developerName: "EcoLiving",
    propertyType: "Townhouse",
    noOfBr: 3,
    clientName: "Adam Clarke",
    agentName: "Fatima Noor",
    team: "Greenline Realty",
    propertyPrice: 980000,
    grossCommissionInclVAT: 53900,
    grossCommission: 51333,
    vat: 2567,
    mondusCommission: 4000,
    leadSource: "Website",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 20000,
    secondPaymentReceived: 20000,
    thirdPaymentReceived: 13900,
    totalPaymentReceived: 53900,
    amountReceivable: 0,
  },
  {
    date: "2025-03-15",
    transactionType: "Sale",
    dealType: "secondary",
    projectName: "Palm Residences",
    unitNo: "C3-09",
    developerName: "Island Developers",
    propertyType: "Penthouse",
    noOfBr: 5,
    clientName: "Maria Lopez",
    agentName: "Ahmed Rizvi",
    team: "Luxury Line",
    propertyPrice: 5000000,
    grossCommissionInclVAT: 250000,
    grossCommission: 238095,
    vat: 11905,
    mondusCommission: 15000,
    leadSource: "Walk-in",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 125000,
    secondPaymentReceived: 80000,
    thirdPaymentReceived: 45000,
    totalPaymentReceived: 250000,
    amountReceivable: 0,
  },
  {
    date: "2025-03-10",
    transactionType: "Rent",
    dealType: "secondary",
    projectName: "Downtown Views",
    unitNo: "D410",
    developerName: "Urban Builders",
    propertyType: "Studio",
    noOfBr: 1,
    clientName: "Kevin Wong",
    agentName: "Zara Syed",
    team: "City Nest",
    propertyPrice: 65000,
    grossCommissionInclVAT: 3250,
    grossCommission: 3095,
    vat: 155,
    mondusCommission: 500,
    leadSource: "Social Media",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 3250,
    secondPaymentReceived: 0,
    thirdPaymentReceived: 0,
    totalPaymentReceived: 3250,
    amountReceivable: 0,
  },
  {
    date: "2025-03-05",
    transactionType: "Sale",
    dealType: "offplan",
    projectName: "Lakeside Towers",
    unitNo: "1107",
    developerName: "Skybuild Ltd.",
    propertyType: "Apartment",
    noOfBr: 2,
    clientName: "Lena Morris",
    agentName: "Bilal Khan",
    team: "Uptown Team",
    propertyPrice: 890000,
    grossCommissionInclVAT: 46700,
    grossCommission: 44476,
    vat: 2224,
    mondusCommission: 3500,
    leadSource: "Event",
    invoiceStatus: "Not Invoiced",
    paymentReceived: false,
    firstPaymentReceived: 0,
    secondPaymentReceived: 0,
    thirdPaymentReceived: 0,
    totalPaymentReceived: 0,
    amountReceivable: 46700,
  },
  {
    date: "2025-02-27",
    transactionType: "Sale",
    dealType: "offplan",
    projectName: "Harmony Heights",
    unitNo: "F606",
    developerName: "Zenith Holdings",
    propertyType: "Duplex",
    noOfBr: 4,
    clientName: "Oscar Reed",
    agentName: "Meera Patel",
    team: "Harmony Homes",
    propertyPrice: 1450000,
    grossCommissionInclVAT: 72500,
    grossCommission: 69048,
    vat: 3452,
    mondusCommission: 5000,
    leadSource: "Cold Call",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 40000,
    secondPaymentReceived: 20000,
    thirdPaymentReceived: 12500,
    totalPaymentReceived: 72500,
    amountReceivable: 0,
  },
  {
    date: "2025-02-20",
    transactionType: "Rent",
    dealType: "secondary",
    projectName: "Metro One",
    unitNo: "305B",
    developerName: "Metro Builders",
    propertyType: "Apartment",
    noOfBr: 2,
    clientName: "Nina Kapoor",
    agentName: "Tariq Hassan",
    team: "Rent Masters",
    propertyPrice: 85000,
    grossCommissionInclVAT: 4250,
    grossCommission: 4048,
    vat: 202,
    mondusCommission: 700,
    leadSource: "Flyer",
    invoiceStatus: "Not Invoiced",
    paymentReceived: false,
    firstPaymentReceived: 0,
    secondPaymentReceived: 0,
    thirdPaymentReceived: 0,
    totalPaymentReceived: 0,
    amountReceivable: 4250,
  },
  {
    date: "2025-02-14",
    transactionType: "Sale",
    dealType: "offplan",
    projectName: "Coral Bay",
    unitNo: "V22",
    developerName: "Marina Developments",
    propertyType: "Villa",
    noOfBr: 5,
    clientName: "George Miller",
    agentName: "Layla Hamdan",
    team: "Prestige Living",
    propertyPrice: 3200000,
    grossCommissionInclVAT: 160000,
    grossCommission: 152380,
    vat: 7620,
    mondusCommission: 10000,
    leadSource: "Website",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 80000,
    secondPaymentReceived: 40000,
    thirdPaymentReceived: 40000,
    totalPaymentReceived: 160000,
    amountReceivable: 0,
  },
  {
    date: "2025-02-10",
    transactionType: "Sale",
    dealType: "secondary",
    projectName: "Skyview Lofts",
    unitNo: "1801",
    developerName: "Future Developments",
    propertyType: "Loft",
    noOfBr: 2,
    clientName: "Angela Brooks",
    agentName: "Samir Ahmed",
    team: "Skyline Sales",
    propertyPrice: 1100000,
    grossCommissionInclVAT: 55000,
    grossCommission: 52381,
    vat: 2619,
    mondusCommission: 4000,
    leadSource: "Instagram",
    invoiceStatus: "Invoiced",
    paymentReceived: true,
    firstPaymentReceived: 27500,
    secondPaymentReceived: 15000,
    thirdPaymentReceived: 12500,
    totalPaymentReceived: 55000,
    amountReceivable: 0,
  },
];

export const agentLastTransactions = [
  {
    agent: "Sarah Ali",
    joiningDate: "2021-05-15",
    lastDealDate: "2025-03-30",
    project: "Sunset Villas",
    amount: 1500000,
    grossComms: 75000,
    monthsWithoutClosing: 0,
  },
  {
    agent: "Omar Khalid",
    joiningDate: "2023-01-10",
    lastDealDate: "2025-02-20",
    project: "Ocean Heights",
    amount: 120000,
    grossComms: 6300,
    monthsWithoutClosing: 1,
  },
  {
    agent: "Fatima Noor",
    joiningDate: "2022-03-22",
    lastDealDate: "2025-01-18",
    project: "Green Meadows",
    amount: 980000,
    grossComms: 53900,
    monthsWithoutClosing: 3,
  },
  {
    agent: "Ahmed Rizvi",
    joiningDate: "2020-11-05",
    lastDealDate: "2025-03-15",
    project: "Palm Residences",
    amount: 5000000,
    grossComms: 250000,
    monthsWithoutClosing: 0,
  },
  {
    agent: "Zara Syed",
    joiningDate: "2024-02-14",
    lastDealDate: "2025-02-10",
    project: "Downtown Views",
    amount: 65000,
    grossComms: 3250,
    monthsWithoutClosing: 2,
  },
  {
    agent: "Bilal Khan",
    joiningDate: "2021-08-30",
    lastDealDate: "2024-12-29",
    project: "Lakeside Towers",
    amount: 890000,
    grossComms: 46700,
    monthsWithoutClosing: 4,
  },
  {
    agent: "Meera Patel",
    joiningDate: "2019-06-01",
    lastDealDate: "2025-02-27",
    project: "Harmony Heights",
    amount: 1450000,
    grossComms: 72500,
    monthsWithoutClosing: 1,
  },
  {
    agent: "Tariq Hassan",
    joiningDate: "2023-05-11",
    lastDealDate: "2024-11-22",
    project: "Metro One",
    amount: 85000,
    grossComms: 4250,
    monthsWithoutClosing: 5,
  },
  {
    agent: "Layla Hamdan",
    joiningDate: "2020-01-10",
    lastDealDate: "2025-01-12",
    project: "Coral Bay",
    amount: 3200000,
    grossComms: 160000,
    monthsWithoutClosing: 3,
  },
  {
    agent: "Samir Ahmed",
    joiningDate: "2022-10-19",
    lastDealDate: "2025-03-05",
    project: "Skyview Lofts",
    amount: 1100000,
    grossComms: 55000,
    monthsWithoutClosing: 1,
  },
];

export const salesTeams = [
  {
    teamName: "Dream Team",
    head: "Sarah Ali",
    members: [
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
      { name: "Sarah Ali", position: null }, // Head
      { name: "Ali Hassan", position: "Senior Agent" },
      { name: "Rana Kapoor", position: "Agent" },
      { name: "Meenal Rao", position: "Junior Agent" },
      { name: "Usman Sheikh", position: "Trainee" },
    ],
  },
  {
    teamName: "Elite Realty",
    head: "Omar Khalid",
    members: [
      { name: "Omar Khalid", position: null },
      { name: "Zoya Qureshi", position: "Senior Agent" },
      { name: "Faizan Memon", position: "Agent" },
      { name: "Nadia Hussain", position: "Trainee" },
    ],
  },
  {
    teamName: "Greenline Realty",
    head: "Fatima Noor",
    members: [
      { name: "Fatima Noor", position: null },
      { name: "Hassan Jameel", position: "Senior Agent" },
      { name: "Sana Malik", position: "Agent" },
      { name: "Rehan Ansari", position: "Junior Agent" },
    ],
  },
  {
    teamName: "Luxury Line",
    head: "Ahmed Rizvi",
    members: [
      { name: "Ahmed Rizvi", position: null },
      { name: "Laila Shah", position: "Senior Agent" },
      { name: "Karan Singh", position: "Agent" },
      { name: "Ayesha Iqbal", position: "Junior Agent" },
      { name: "Bilal Mehmood", position: "Trainee" },
    ],
  },
  {
    teamName: "City Nest",
    head: "Zara Syed",
    members: [
      { name: "Zara Syed", position: null },
      { name: "Junaid Khan", position: "Agent" },
      { name: "Neha Desai", position: "Junior Agent" },
      { name: "Rizwan Haider", position: "Trainee" },
    ],
  },
  {
    teamName: "Uptown Team",
    head: "Bilal Khan",
    members: [
      { name: "Bilal Khan", position: null },
      { name: "Yasmeen Farooqi", position: "Senior Agent" },
      { name: "Talha Bhatti", position: "Agent" },
      { name: "Zainab Raza", position: "Trainee" },
    ],
  },
  {
    teamName: "Harmony Homes",
    head: "Meera Patel",
    members: [
      { name: "Meera Patel", position: null },
      { name: "Anjali Ghosh", position: "Senior Agent" },
      { name: "Rajeev Thomas", position: "Agent" },
      { name: "Faisal Nadeem", position: "Junior Agent" },
      { name: "Tanya Lobo", position: "Trainee" },
    ],
  },
  {
    teamName: "Rent Masters",
    head: "Tariq Hassan",
    members: [
      { name: "Tariq Hassan", position: null },
      { name: "Imran Mir", position: "Agent" },
      { name: "Nimra Abbasi", position: "Junior Agent" },
      { name: "Kabir Sayeed", position: "Trainee" },
    ],
  },
  {
    teamName: "Prestige Living",
    head: "Layla Hamdan",
    members: [
      { name: "Layla Hamdan", position: null },
      { name: "Sameer Siddiqui", position: "Senior Agent" },
      { name: "Hina Bukhari", position: "Agent" },
      { name: "Adeel Waris", position: "Junior Agent" },
    ],
  },
  {
    teamName: "Skyline Sales",
    head: "Samir Ahmed",
    members: [
      { name: "Samir Ahmed", position: null },
      { name: "Fariha Nadeem", position: "Senior Agent" },
      { name: "Danish Khan", position: "Agent" },
      { name: "Maya Fernandes", position: "Junior Agent" },
      { name: "Owais Malik", position: "Trainee" },
    ],
  },
];

export const agentRankingData = {
  2024: {
    January: [
      { name: "Alice Johnson", grossCommission: 15000, rank: 1 },
      { name: "Bob Smith", grossCommission: 12500, rank: 2 },
      { name: "Charlie Davis", grossCommission: 9800, rank: 3 },
      { name: "Diana Lee", grossCommission: 8700, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7200, rank: 5 },
    ],
    February: [
      { name: "Alice Johnson", grossCommission: 14200, rank: 1 },
      { name: "Charlie Davis", grossCommission: 13800, rank: 2 },
      { name: "Bob Smith", grossCommission: 13000, rank: 3 },
      { name: "Diana Lee", grossCommission: 8800, rank: 4 },
      { name: "Ethan Clark", grossCommission: 6500, rank: 5 },
    ],
    March: [
      { name: "Charlie Davis", grossCommission: 15800, rank: 1 },
      { name: "Alice Johnson", grossCommission: 14900, rank: 2 },
      { name: "Bob Smith", grossCommission: 12600, rank: 3 },
      { name: "Diana Lee", grossCommission: 9700, rank: 4 },
      { name: "Ethan Clark", grossCommission: 6900, rank: 5 },
    ],
    April: [
      { name: "Alice Johnson", grossCommission: 16000, rank: 1 },
      { name: "Charlie Davis", grossCommission: 15000, rank: 2 },
      { name: "Bob Smith", grossCommission: 13200, rank: 3 },
      { name: "Diana Lee", grossCommission: 9200, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7400, rank: 5 },
    ],
    May: [
      { name: "Charlie Davis", grossCommission: 16200, rank: 1 },
      { name: "Alice Johnson", grossCommission: 15700, rank: 2 },
      { name: "Bob Smith", grossCommission: 12800, rank: 3 },
      { name: "Diana Lee", grossCommission: 9100, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7000, rank: 5 },
    ],
    June: [
      { name: "Alice Johnson", grossCommission: 16800, rank: 1 },
      { name: "Charlie Davis", grossCommission: 16100, rank: 2 },
      { name: "Bob Smith", grossCommission: 12900, rank: 3 },
      { name: "Diana Lee", grossCommission: 9500, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7200, rank: 5 },
    ],
    July: [
      { name: "Charlie Davis", grossCommission: 17000, rank: 1 },
      { name: "Alice Johnson", grossCommission: 16900, rank: 2 },
      { name: "Bob Smith", grossCommission: 13400, rank: 3 },
      { name: "Diana Lee", grossCommission: 8800, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7500, rank: 5 },
    ],
    August: [
      { name: "Alice Johnson", grossCommission: 17500, rank: 1 },
      { name: "Charlie Davis", grossCommission: 16900, rank: 2 },
      { name: "Bob Smith", grossCommission: 13200, rank: 3 },
      { name: "Diana Lee", grossCommission: 9200, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7000, rank: 5 },
    ],
    September: [
      { name: "Charlie Davis", grossCommission: 18000, rank: 1 },
      { name: "Alice Johnson", grossCommission: 17800, rank: 2 },
      { name: "Bob Smith", grossCommission: 13700, rank: 3 },
      { name: "Diana Lee", grossCommission: 9000, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7600, rank: 5 },
    ],
    October: [
      { name: "Alice Johnson", grossCommission: 18100, rank: 1 },
      { name: "Charlie Davis", grossCommission: 17500, rank: 2 },
      { name: "Bob Smith", grossCommission: 13900, rank: 3 },
      { name: "Diana Lee", grossCommission: 9100, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7800, rank: 5 },
    ],
    November: [
      { name: "Charlie Davis", grossCommission: 18500, rank: 1 },
      { name: "Alice Johnson", grossCommission: 17900, rank: 2 },
      { name: "Bob Smith", grossCommission: 14000, rank: 3 },
      { name: "Diana Lee", grossCommission: 8900, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7700, rank: 5 },
    ],
    December: [
      { name: "Alice Johnson", grossCommission: 19000, rank: 1 },
      { name: "Charlie Davis", grossCommission: 18200, rank: 2 },
      { name: "Bob Smith", grossCommission: 14300, rank: 3 },
      { name: "Diana Lee", grossCommission: 9200, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7600, rank: 5 },
    ],
  },
  2025: {
    January: [
      { name: "Charlie Davis", grossCommission: 19200, rank: 1 },
      { name: "Alice Johnson", grossCommission: 18800, rank: 2 },
      { name: "Bob Smith", grossCommission: 14500, rank: 3 },
      { name: "Diana Lee", grossCommission: 9400, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7700, rank: 5 },
    ],
    February: [
      { name: "Alice Johnson", grossCommission: 19400, rank: 1 },
      { name: "Charlie Davis", grossCommission: 19000, rank: 2 },
      { name: "Bob Smith", grossCommission: 14700, rank: 3 },
      { name: "Diana Lee", grossCommission: 9300, rank: 4 },
      { name: "Ethan Clark", grossCommission: 7800, rank: 5 },
    ],
    March: [
      { name: "Charlie Davis", grossCommission: 19800, rank: 1 },
      { name: "Alice Johnson", grossCommission: 19300, rank: 2 },
      { name: "Bob Smith", grossCommission: 15000, rank: 3 },
      { name: "Diana Lee", grossCommission: 9500, rank: 4 },
      { name: "Ethan Clark", grossCommission: 8000, rank: 5 },
    ],
  },
};

export const developerData = {
  2024: {
    January: {
      closedDeals: 12,
      propertyPrice: 15000000,
      grossCommission: 750000,
      netCommission: 600000,
      totalPaymentReceived: 550000,
      amountReceivable: 50000,
      developerName: "Heart of Europe",
    },
    February: {
      closedDeals: 10,
      propertyPrice: 12500000,
      grossCommission: 625000,
      netCommission: 500000,
      totalPaymentReceived: 450000,
      amountReceivable: 50000,
      developerName: "Danube",
    },
    March: {
      closedDeals: 15,
      propertyPrice: 18000000,
      grossCommission: 900000,
      netCommission: 720000,
      totalPaymentReceived: 700000,
      amountReceivable: 20000,
      developerName: "Azizi",
    },
    April: {
      closedDeals: 18,
      propertyPrice: 21000000,
      grossCommission: 1050000,
      netCommission: 840000,
      totalPaymentReceived: 800000,
      amountReceivable: 40000,
      developerName: "Aldar",
    },
    May: {
      closedDeals: 14,
      propertyPrice: 16000000,
      grossCommission: 800000,
      netCommission: 640000,
      totalPaymentReceived: 600000,
      amountReceivable: 40000,
      developerName: "Devmark",
    },
    June: {
      closedDeals: 16,
      propertyPrice: 17500000,
      grossCommission: 875000,
      netCommission: 700000,
      totalPaymentReceived: 650000,
      amountReceivable: 50000,
      developerName: "Arada",
    },
    July: {
      closedDeals: 13,
      propertyPrice: 14500000,
      grossCommission: 725000,
      netCommission: 580000,
      totalPaymentReceived: 540000,
      amountReceivable: 40000,
      developerName: "Secondary",
    },
    August: {
      closedDeals: 17,
      propertyPrice: 20000000,
      grossCommission: 1000000,
      netCommission: 800000,
      totalPaymentReceived: 760000,
      amountReceivable: 40000,
      developerName: "SOL",
    },
    September: {
      closedDeals: 19,
      propertyPrice: 22000000,
      grossCommission: 1100000,
      netCommission: 880000,
      totalPaymentReceived: 830000,
      amountReceivable: 50000,
      developerName: "Heart of Europe",
    },
    October: {
      closedDeals: 21,
      propertyPrice: 25000000,
      grossCommission: 1250000,
      netCommission: 1000000,
      totalPaymentReceived: 950000,
      amountReceivable: 50000,
      developerName: "Danube",
    },
    November: {
      closedDeals: 20,
      propertyPrice: 24000000,
      grossCommission: 1200000,
      netCommission: 960000,
      totalPaymentReceived: 910000,
      amountReceivable: 50000,
      developerName: "Azizi",
    },
    December: {
      closedDeals: 22,
      propertyPrice: 26000000,
      grossCommission: 1300000,
      netCommission: 1040000,
      totalPaymentReceived: 990000,
      amountReceivable: 50000,
      developerName: "Arada",
    },
  },
  2025: {
    January: {
      closedDeals: 23,
      propertyPrice: 27000000,
      grossCommission: 1350000,
      netCommission: 1080000,
      totalPaymentReceived: 1000000,
      amountReceivable: 80000,
      developerName: "Devmark",
    },
    February: {
      closedDeals: 21,
      propertyPrice: 25000000,
      grossCommission: 1250000,
      netCommission: 1000000,
      totalPaymentReceived: 950000,
      amountReceivable: 50000,
      developerName: "Aldar",
    },
    March: {
      closedDeals: 24,
      propertyPrice: 28000000,
      grossCommission: 1400000,
      netCommission: 1120000,
      totalPaymentReceived: 1060000,
      amountReceivable: 60000,
      developerName: "SOL",
    },
    April: {
      closedDeals: 20,
      propertyPrice: 23000000,
      grossCommission: 1150000,
      netCommission: 920000,
      totalPaymentReceived: 880000,
      amountReceivable: 40000,
      developerName: "Secondary",
    },
  },
};
